### ISSUE TITLE
Support for Command Line Login

### ISSUE THREAD

**Issue by zethon** [zethon/arcc#10]
Reddit's Oath2 requires that the user have desktop access in order to authenticate since authentication is required through a browser. This could be avoided, however, by:

- [ ] <s>asking the user for their username/password</s> (See #11)
- [ ] <s>doing a standard login request using the `curl` libs</s> (See #11)
- [ ] <s>HTML scraping the response and upon a successful login...</s> (See #11)
- [x] issue the Oauth2 url using `curl`
- [x] submitting the request as though the user pressed "allow"

Logging in using this method should be optional on the `login` command. Perhaps something like `login -cll` or whatever.
